# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vyos/protos/vyos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16vyos/protos/vyos.proto\"\"\n\x10SetConfigRequest\x12\x0e\n\x06\x63onfig\x18\x01 \x01(\t\"!\n\x0eSetConfigReply\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x12\n\x10GetConfigRequest\" \n\x0eGetConfigReply\x12\x0e\n\x06\x63onfig\x18\x01 \x01(\t\"$\n\x0fRxpacketRequest\x12\x11\n\tinterface\x18\x01 \x01(\t\"3\n\rRxpacketReply\x12\x11\n\trxpackets\x18\x01 \x01(\x04\x12\x0f\n\x07message\x18\x02 \x01(\t2\xe7\x01\n\x11VyosConfigService\x12\x31\n\tSetConfig\x12\x11.SetConfigRequest\x1a\x0f.SetConfigReply\"\x00\x12\x31\n\tGetConfig\x12\x11.GetConfigRequest\x1a\x0f.GetConfigReply\"\x00\x12\x31\n\x0bGetCounters\x12\x10.RxpacketRequest\x1a\x0e.RxpacketReply\"\x00\x12\x39\n\x11GetCountersStream\x12\x10.RxpacketRequest\x1a\x0e.RxpacketReply\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vyos.protos.vyos_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SETCONFIGREQUEST']._serialized_start=26
  _globals['_SETCONFIGREQUEST']._serialized_end=60
  _globals['_SETCONFIGREPLY']._serialized_start=62
  _globals['_SETCONFIGREPLY']._serialized_end=95
  _globals['_GETCONFIGREQUEST']._serialized_start=97
  _globals['_GETCONFIGREQUEST']._serialized_end=115
  _globals['_GETCONFIGREPLY']._serialized_start=117
  _globals['_GETCONFIGREPLY']._serialized_end=149
  _globals['_RXPACKETREQUEST']._serialized_start=151
  _globals['_RXPACKETREQUEST']._serialized_end=187
  _globals['_RXPACKETREPLY']._serialized_start=189
  _globals['_RXPACKETREPLY']._serialized_end=240
  _globals['_VYOSCONFIGSERVICE']._serialized_start=243
  _globals['_VYOSCONFIGSERVICE']._serialized_end=474
# @@protoc_insertion_point(module_scope)
